name: robo_front
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_spinkit: ^4.1.2
  flutter_staggered_grid_view: ^0.4.0
  http: ^0.13.3
  flutter:
    sdk: flutter
  
  bubble_bottom_bar: ^1.2.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
